### ISSUE TITLE
Other Health Data?

### ISSUE THREAD

**Issue by gorfreed** [mm/heartbridge#2]
It's a shame you limited your tool to heartrate only. I for example would be much more interested in other of my Apple Health data points (e.g. steps!!) for the very same reason as you - to visualize the data e.g. on a web-accessible dashboard. Would it be difficult to modify the script so it can receive the other data obtained by the iOS fetch shortcut and insert it into a mysql database?

**Comment by mm** [comment]
Sorry for the late response on this one! I'm definitely open to adding support for more types of data points -- would steps be the biggest one for you?

I can also look into adding support for pushing to a database! Would MySQL be the main one you're interested in? The application would be managing its own tables within whatever database you point it at.

**Comment by mathematicalmichael** [comment]
I'd like that for sure, as well as flights climbed, miles biked.

great project!

**Comment by mm** [comment]
Sure! I'll look into ways to add those in, thanks a lot 😄

**Comment by mm** [comment]
Just released a new version that covers adding these new data types! ([v2.0.0](https://github.com/mm/heartbridge/releases/tag/v2.0.0)) As a heads up it will require a new version of the shortcut, which is linked in the release notes and the README. Enjoy 😄
